### ISSUE TITLE
关于d4j项目中的oralce文件创建规则问题

### ISSUE THREAD

**Issue by ZhuHandong** [Ultimanecat/DefectRepairing#12]
学长您好，非常抱歉打扰到您，最近我读了《Fault Localization via Efficient Probabilistic Modeling ofProgram Semantic》，里面实验中的oracle文件是您手动标注的上传的，对于具体怎么根据src.patch去手动创建oracle文件，我非常迷惑，恳请您的指教。

**Comment by xiongyingfei** [comment]
这是关于另一个仓库的问题，吴宜谦应该已经邮件回复了。
