### ISSUE TITLE
Probably typos in patch files - Reapir should be Repair?

### ISSUE THREAD

**Issue by maxxbw54** [Ultimanecat/DefectRepairing#8]
Hi folks, appreciate for releasing your experiment data. Interesting work!

I am wondering there are some typos probably exist in [patch files](https://github.com/Ultimanecat/DefectRepairing/tree/master/tool/patches). In particular, from _PatchHDRepair1_ to _PatchHDRepair10_, the diff info of patch file _projectName_PatchHDRe**pa**irK_ is mistakenly (probably) written as _projectName_PatchHDRe**ap**irK_.

I notice this issue because I failed to use diff information in those files to localize patch file. And it works when I correct the typos. Please kindly check and advise.

**Comment by Ultimanecat** [comment]
Thank you for using our tool! We have noticed that typo but we only fixed the filename.
While using unix **patch** command this should work fine although the typo exists.
Thank you for noticing this bug and we'll be on it.
