### ISSUE TITLE
Empty buggy & buggy_e files

### ISSUE THREAD

**Issue by khesoem-old** [Ultimanecat/DefectRepairing#9]
Hi. Thank you for your interesting paper&tool.

When I use the example command to see results (python3 run.py Chart 1 Patch1), the patch is labeled as "Correct" and no error occurs; however, all the files in ../traces/Chart1bPatch/buggy & buggy_e folders seem empty. All files in buggy_e are literally empty and all files in buggy contain only one line (### BTrace Log: ...).

Am I doing something wrong? I think these files should not be empty and the result label should be "Incorrect".

Note: After running run.py is finished, there is no AllLines.class in lib/btrace folder. I thought it may be related.

**Comment by xinyuan-liu** [comment]
Is there an AllLines.java in lib/btrace folder? Does the file lib/btrace/btracec have the execute permission?  What if you manually run the command 'btracec Allines.java'?

**Comment by Ultimanecat** [comment]
We're already on it. It seems that you have met something we didn't expect. Can you provide more bug info? It will greatly help us to solve your problem. 
Also, we suggest you take a double check about the requirements provided in Readme(like d4j, python, java7, etc.)
Maybe we will also give an option for you to use our own tracer rather than Btrace as a backup although it has been deprecated.

**Comment by khesoem-old** [comment]
Thank you @xinyuan-liu 
The problem was related to Java. Actually, I had installed java; nonetheless, I had not set JAVA_HOME. I think it makes sense to note that users should set JAVA_HOME before using the tool.

**Comment by ShangwenWang** [comment]
Hello everyone,
I'd like to know is this trace in get_test_coverage.py correct?
![图片](https://user-images.githubusercontent.com/59810938/74302112-3ea74380-4d90-11ea-8990-209d90048e18.png)
When I executing in my PC, there is an error:
![图片](https://user-images.githubusercontent.com/59810938/74302156-6e564b80-4d90-11ea-8c4d-82593849d7b5.png)

**Comment by ShangwenWang** [comment]
@khesoem @xinyuan-liu @Ultimanecat Anyone can help me?
